### ISSUE TITLE
我觉得这两个地方设计的不好

### ISSUE THREAD

**Issue by wanyaoqi** [TanLian/testrpc#1]
https://github.com/TanLian/testrpc/blob/23063026ffae807dd3d2062266a577aa8f7af6d2/testrpc/server.go#L45
你把函数的参数打包放入第一个参数内我觉得不好，你这样需要使用者配合你去编写函数的代码，而不是直接register一个写好的函数就能用；
我觉得可以遍历一遍函数的参数来取各个参数的类型
返回值也可以这么做
https://github.com/TanLian/testrpc/blob/23063026ffae807dd3d2062266a577aa8f7af6d2/testrpc/server.go#L46

还有rpc调用函数如果panic了也没有处理（我觉得可以把panic的结果返回）

**Comment by TanLian** [comment]
我仔细阅读了描述，您的意思应该是在server端可以注册一个函数（现在的做法是注册对象），在client端可以直接调用这个函数，我觉得这个可以，感谢建议。

**Comment by TanLian** [comment]
后期依然会保留注册对象的接口，但可能会增加接口，如注册函数。
